version: '3'
services:
  playground-web-frontend:
    image: danielracolta/playground-web-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://playground-web-backend:8080/
    ports:
      - 3000:3000
  playground-web-backend:
    image: danielracolta/playground-web-backend:latest
    environment:
      MONGODB_URI: mongodb+srv://<243032>:<CGfNDTtZq726laO2>@<Cluster0>/todo?retryWrites=true&w=majority
    ports:
      - 8080:8080